/*
 * Copyright (C) 2024 Inspur Group Co., Ltd. Unpublished
 *
 * Inspur Group Co., Ltd.
 * Proprietary & Confidential
 *
 * This source code and the algorithms implemented therein constitute
 * confidential information and may comprise trade secrets of Inspur
 * or its associates, and any use thereof is subject to the terms and
 * conditions of the Non-Disclosure Agreement pursuant to which this
 * source code was originally received.
 */

#ifndef _HRIF_TRANSACT_CODE_H_
#define _HRIF_TRANSACT_CODE_H_

// category    method
// xxxx xxxx   yyyy yyyy

#define HRIF_TRANSACT_CODE_CATEGORY_MASK 0xFFFFFF00
#define HRIF_TRANSACT_CODE_METHOD_MASK 0xFF

enum {
    HRIF_TRANSACT_CODE_SYSTEM_BASE = 0 << 8,
    HRIF_TRANSACT_CODE_NETWORK_BASE = 1 << 8,
    HRIF_TRANSACT_CODE_WIRELESS_BASE = 2 << 8
};

enum {
    HRIF_TRANSACT_CODE_SYSTEM_INIT = HRIF_TRANSACT_CODE_SYSTEM_BASE,

};

enum {
    HRIF_TRANSACT_CODE_NETWORK_INIT = HRIF_TRANSACT_CODE_NETWORK_BASE,
    HRIF_TRANSACT_CODE_NETWORK_WAN_SIZE,
    HRIF_TRANSACT_CODE_NETWORK_WAN_ARRAY,
    HRIF_TRANSACT_CODE_NETWORK_WAN_GET,
    HRIF_TRANSACT_CODE_NETWORK_WAN_GET_PROTO,
    HRIF_TRANSACT_CODE_NETWORK_WAN_SET_PROTO,
    HRIF_TRANSACT_CODE_NETWORK_WAN_GET_IPV4,
    HRIF_TRANSACT_CODE_NETWORK_WAN_SET_IPV4,
    HRIF_TRANSACT_CODE_NETWORK_WAN_GET_IPV6,
    HRIF_TRANSACT_CODE_NETWORK_WAN_SET_IPV6,
    HRIF_TRANSACT_CODE_NETWORK_WAN_GET_PPPOE,
    HRIF_TRANSACT_CODE_NETWORK_WAN_SET_PPPOE,
    HRIF_TRANSACT_CODE_NETWORK_WAN_COMMIT,
    HRIF_TRANSACT_CODE_NETWORK_WAN_STATUS,
    HRIF_TRANSACT_CODE_NETWORK_WAN_NETSTATS,
    HRIF_TRANSACT_CODE_NETWORK_GET_WORKMODE,
    HRIF_TRANSACT_CODE_NETWORK_SET_WORKMODE,
    HRIF_TRANSACT_CODE_NETWORK_LAN_GET,
    HRIF_TRANSACT_CODE_NETWORK_LAN_SET,
    HRIF_TRANSACT_CODE_NETWORK_DHCP_GET,
    HRIF_TRANSACT_CODE_NETWORK_DHCP_SET,
    HRIF_TRANSACT_CODE_NETWORK_LANHOST_SIZE,
    HRIF_TRANSACT_CODE_NETWORK_LANHOST_ARRAY,
    HRIF_TRANSACT_CODE_NETWORK_LANHOST_ONLINE_SIZE,
    HRIF_TRANSACT_CODE_NETWORK_LANHOST_LIMITSPEED_SET,
    HRIF_TRANSACT_CODE_NETWORK_LIMIT_GET,
    HRIF_TRANSACT_CODE_NETWORK_LIMIT_SET,
    HRIF_TRANSACT_CODE_NETWORK_LIMIT_DEL,
    HRIF_TRANSACT_CODE_NETWORK_PORT_FORWARDING_ADD,
    HRIF_TRANSACT_CODE_NETWORK_PORT_FORWARDING_MOD,
    HRIF_TRANSACT_CODE_NETWORK_PORT_FORWARDING_DEL,
    HRIF_TRANSACT_CODE_NETWORK_PORT_FORWARDING_ARRAY,
    HRIF_TRANSACT_CODE_NETWORK_DMZ_GET,
    HRIF_TRANSACT_CODE_NETWORK_DMZ_SET,

};

#endif  //_HRIF_TRANSACT_CODE_H_
