/*
 * Copyright (C) 2024 Inspur Group Co., Ltd. Unpublished
 *
 * Inspur Group Co., Ltd.
 * Proprietary & Confidential
 *
 * This source code and the algorithms implemented therein constitute
 * confidential information and may comprise trade secrets of Inspur
 * or its associates, and any use thereof is subject to the terms and
 * conditions of the Non-Disclosure Agreement pursuant to which this
 * source code was originally received.
 */

#ifndef _HRIF_TRANSACT_CODE_H_
#define _HRIF_TRANSACT_CODE_H_

// category    method
// xxxx xxxx   yyyy yyyy

#define HRIF_TRANSACT_CODE_CATEGORY_MASK 0xFFFFFF00
#define HRIF_TRANSACT_CODE_ID_MASK 0xFF

enum {
    HRIF_TRANSACT_CODE_SYSTEM_BASE = 0 << 8,
    HRIF_TRANSACT_CODE_NETWORK_BASE = 1 << 8,
    HRIF_TRANSACT_CODE_WIRELESS_BASE = 2 << 8,
    HRIF_TRANSACT_CODE_EASYMESH_BASE = 3 << 8,
    HRIF_TRANSACT_CODE_DISGNHOSTICS_BASE = 4 << 8,
};

enum {
    HRIF_TRANSACT_CODE_SYSTEM_INIT = HRIF_TRANSACT_CODE_SYSTEM_BASE,
    HRIF_TRANSACT_CODE_SYSTEM_BOARD,
    HRIF_TRANSACT_CODE_SYSTEM_STORAGE,
    HRIF_TRANSACT_CODE_SYSTEM_MEMORY,
    HRIF_TRANSACT_CODE_SYSTEM_UPTIME,
    HRIF_TRANSACT_CODE_SYSTEM_TIME_GET,
    HRIF_TRANSACT_CODE_SYSTEM_TIME_SET,
    HRIF_TRANSACT_CODE_SYSTEM_TIMEZONE_GET,
    HRIF_TRANSACT_CODE_SYSTEM_TIMEZONE_SET,
    HRIF_TRANSACT_CODE_SYSTEM_NTP_GET,
    HRIF_TRANSACT_CODE_SYSTEM_NTP_SET,
    HRIF_TRANSACT_CODE_SYSTEM_CPU_JIFFIES,
    HRIF_TRANSACT_CODE_SYSTEM_REBOOT,
    HRIF_TRANSACT_CODE_SYSTEM_RESET,
    HRIF_TRANSACT_CODE_SYSTEM_LED_GET,
    HRIF_TRANSACT_CODE_SYSTEM_LED_SET,
};

enum {
    HRIF_TRANSACT_CODE_NETWORK_INIT = HRIF_TRANSACT_CODE_NETWORK_BASE,
    HRIF_TRANSACT_CODE_NETWORK_WAN_SIZE,
    HRIF_TRANSACT_CODE_NETWORK_WAN_ARRAY,
    HRIF_TRANSACT_CODE_NETWORK_WAN_GET,
    HRIF_TRANSACT_CODE_NETWORK_WAN_GET_PROTO,
    HRIF_TRANSACT_CODE_NETWORK_WAN_SET_PROTO,
    HRIF_TRANSACT_CODE_NETWORK_WAN_GET_IPV4,
    HRIF_TRANSACT_CODE_NETWORK_WAN_SET_IPV4,
    HRIF_TRANSACT_CODE_NETWORK_WAN_GET_IPV6,
    HRIF_TRANSACT_CODE_NETWORK_WAN_SET_IPV6,
    HRIF_TRANSACT_CODE_NETWORK_WAN_GET_PPPOE,
    HRIF_TRANSACT_CODE_NETWORK_WAN_SET_PPPOE,
    HRIF_TRANSACT_CODE_NETWORK_WAN_COMMIT,
    HRIF_TRANSACT_CODE_NETWORK_WAN_DISCARD,
    HRIF_TRANSACT_CODE_NETWORK_WAN_STATUS,
    HRIF_TRANSACT_CODE_NETWORK_WAN_NETSTATS,
    HRIF_TRANSACT_CODE_NETWORK_GET_WORKMODE,
    HRIF_TRANSACT_CODE_NETWORK_SET_WORKMODE,
    HRIF_TRANSACT_CODE_NETWORK_LAN_GET,
    HRIF_TRANSACT_CODE_NETWORK_LAN_SET,
    HRIF_TRANSACT_CODE_NETWORK_DHCP_GET,
    HRIF_TRANSACT_CODE_NETWORK_DHCP_SET,
    HRIF_TRANSACT_CODE_NETWORK_LANHOST_SIZE,
    HRIF_TRANSACT_CODE_NETWORK_LANHOST_ARRAY,
    HRIF_TRANSACT_CODE_NETWORK_LANHOST_ONLINE_SIZE,
    HRIF_TRANSACT_CODE_NETWORK_LANHOST_LIMITSPEED_SET,
    HRIF_TRANSACT_CODE_NETWORK_LIMIT_GET,
    HRIF_TRANSACT_CODE_NETWORK_LIMIT_SET,
    HRIF_TRANSACT_CODE_NETWORK_LIMIT_DEL,
    HRIF_TRANSACT_CODE_NETWORK_PORT_FORWARDING_ADD,
    HRIF_TRANSACT_CODE_NETWORK_PORT_FORWARDING_MOD,
    HRIF_TRANSACT_CODE_NETWORK_PORT_FORWARDING_DEL,
    HRIF_TRANSACT_CODE_NETWORK_PORT_FORWARDING_ARRAY,
    HRIF_TRANSACT_CODE_NETWORK_DMZ_GET,
    HRIF_TRANSACT_CODE_NETWORK_DMZ_SET,
    HRIF_TRANSACT_CODE_NETWORK_IPTV_GET,
    HRIF_TRANSACT_CODE_NETWORK_IPTV_SET,
    HRIF_TRANSACT_CODE_NETWORK_DOS_GET,
    HRIF_TRANSACT_CODE_NETWORK_DOS_SET,
    HRIF_TRANSACT_CODE_NETWORK_FILTERMODE_GET,
    HRIF_TRANSACT_CODE_NETWORK_FILTERMODE_SET,
    HRIF_TRANSACT_CODE_NETWORK_ADDRESS_FILTER_GET,
    HRIF_TRANSACT_CODE_NETWORK_ADDRESS_FILTER_SET,
    HRIF_TRANSACT_CODE_NETWORK_PORT_FILTER_GET,
    HRIF_TRANSACT_CODE_NETWORK_PORT_FILTER_SET,
    HRIF_TRANSACT_CODE_NETWORK_URL_FILTER_GET,
    HRIF_TRANSACT_CODE_NETWORK_URL_FILTER_SET,
    HRIF_TRANSACT_CODE_NETWORK_QOS_GET,
    HRIF_TRANSACT_CODE_NETWORK_QOS_SET,
    HRIF_TRANSACT_CODE_NETWORK_DUPLEX_MODE,
    // make sure < 0x100
};

enum {
    HRIF_TRANSACT_CODE_WIRELESS_INIT = HRIF_TRANSACT_CODE_WIRELESS_BASE,
    HRIF_TRANSACT_CODE_WIRELESS_CAPABILITY,
    HRIF_TRANSACT_CODE_WIRELESS_RADIO_STATUS,
    HRIF_TRANSACT_CODE_WIRELESS_RADIO_GET,
    HRIF_TRANSACT_CODE_WIRELESS_RADIO_SET,
    HRIF_TRANSACT_CODE_WIRELESS_INTERFACE_GET,
    HRIF_TRANSACT_CODE_WIRELESS_INTERFACE_SET,
    HRIF_TRANSACT_CODE_WIRELESS_BANDSTEERING_GET,
    HRIF_TRANSACT_CODE_WIRELESS_BANDSTEERING_SET,
    HRIF_TRANSACT_CODE_WIRELESS_SCAN_LIST_ARRAY,
    HRIF_TRANSACT_CODE_WIRELESS_SCAN_CONNECT,
    HRIF_TRANSACT_CODE_WIRELESS_SCAN_STATUS,
    HRIF_TRANSACT_CODE_WIRELESS_WPS_GET, // trigger
    HRIF_TRANSACT_CODE_WIRELESS_WPS_SET,
    HRIF_TRANSACT_CODE_WIRELESS_WPS_SWITCH_GET, // switch
    HRIF_TRANSACT_CODE_WIRELESS_WPS_SWITCH_SET,
    HRIF_TRANSACT_CODE_WIRELESS_TIMER_SWITCH_GET,
    HRIF_TRANSACT_CODE_WIRELESS_TIMER_SWITCH_SET,
    HRIF_TRANSACT_CODE_WIRELESS_TIMER_ADD,
    HRIF_TRANSACT_CODE_WIRELESS_TIMER_MOD,
    HRIF_TRANSACT_CODE_WIRELESS_TIMER_DEL,
    HRIF_TRANSACT_CODE_WIRELESS_TIMER_ARRAY,
    HRIF_TRANSACT_CODE_WIRELESS_DEASSOCIATE,
    HRIF_TRANSACT_CODE_WIRELESS_CHANNEL_SCAN,
    HRIF_TRANSACT_CODE_WIRELESS_CHANNEL_SCORE_GET,
    HRIF_TRANSACT_CODE_WIRELESS_VSIE_GET,
    HRIF_TRANSACT_CODE_WIRELESS_VSIE_BEACONTX_SET,
    HRIF_TRANSACT_CODE_WIRELESS_VSIE_BEACONTX_LST,
    HRIF_TRANSACT_CODE_WIRELESS_VSIE_PROBERX_SET,
    HRIF_TRANSACT_CODE_WIRELESS_VSIE_PROBERX_LST,
};

enum {
    HRIF_TRANSACT_CODE_EASYMESH_INIT = HRIF_TRANSACT_CODE_EASYMESH_BASE,
    HRIF_TRANSACT_CODE_EASYMESH_ROLE_SET,
    HRIF_TRANSACT_CODE_EASYMESH_ROLE_GET,
    HRIF_TRANSACT_CODE_EASYMESH_WPS,
    HRIF_TRANSACT_CODE_EASYMESH_ROAMING_SET,
    HRIF_TRANSACT_CODE_EASYMESH_INFO_GET,
    HRIF_TRANSACT_CODE_EASYMESH_TOPO_GET,
    HRIF_TRANSACT_CODE_EASYMESH_BACKHAULBSS_GET,
};


#endif  //_HRIF_TRANSACT_CODE_H_
